### ISSUE TITLE
MPI+OpenMP hybrid parallelization

### ISSUE THREAD

**Issue by ybC007** [ttadano/alamode#72] opened 2022-04-27 01:54 UTC
Hi! I use MPI + OpenMP hybrid parallelization to calculate the thermal conductivity on several nodes. But I found that only the CPU of the first node is running while CPU of other nodes are not running.
![screenshot](https://user-images.githubusercontent.com/55368735/165422449-cd0e28b2-68de-4dea-a8bd-d68abf468efb.jpg)
![screenshot](https://user-images.githubusercontent.com/55368735/165422563-96fa4591-9417-4e0f-9ea7-501cddd34fb4.jpg)

**Comment by ttadano** [comment] 2022-04-27 02:28
It not clear if the issue is related to alamode. Did you see this issue only with alamode?

**Comment by ttadano** [comment] 2022-11-10 11:28
Close this issue. Reopen it when necessary.

**Closed by ttadano** 2022-11-10 11:28 UTC
